# # Membuat List awal
# daftar_belanja = ["telur", "roti", "susu"]

# # Menambahkan item baru "keju"
# daftar_belanja.append("keju")

# # Menghapus item "roti"
# daftar_belanja.remove("roti")

# # Menampilkan isi daftar belanja terbaru
# print("Daftar belanja terbaru:", daftar_belanja)

#LIST

# kelas = ['alpro', 'pti', 'matdis']
# kelas.append('epsi')
# print(kelas)

# kelas = ['alpro', 'pti', 'matdis', 'pancasila']
# kelas.remove('pti')
# print(kelas)
# del kelas[2]
# print(kelas)

#TUPLE

# game = ('ML', 'FF', 'PUBG', 'ROBLOX')
# print(game[3])

# hari = ('senin', 'selasa', 'rabu')
# print(hari)
# hariBaru = hari + ('kamis', 'jumat',)
# print ("hari yang diperbarui yaitu: ", hariBaru)

# WARNA1 = ('BIRU', 'MERAH', 'KUNING')
# WARNA2 = ('HIJAU', 'COKELAT')
# del WARNA2
# print(WARNA1)